// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_date_LBL;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_offBAR;
lv_obj_t * ui_offTimeLBL1;
lv_obj_t * ui_Label40;
void ui_event_mainSWbtn1(lv_event_t * e);
lv_obj_t * ui_mainSWbtn1;
lv_obj_t * ui_swLBL1;
lv_obj_t * ui_timeLBL;
lv_obj_t * ui_secLBL;
lv_obj_t * ui_batLBL;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label4;
lv_obj_t * ui_batLBL1;
lv_obj_t * ui_mainFormatLBL;
lv_obj_t * ui_swLBL2;
lv_obj_t * ui_swLBL3;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_batBAR;
lv_obj_t * ui_brightLBL2;
void ui_event_mainSWbtn2(lv_event_t * e);
lv_obj_t * ui_mainSWbtn2;
void ui_event_mainSWbtn3(lv_event_t * e);
lv_obj_t * ui_mainSWbtn3;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label43;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label44;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_yearLBL1;
lv_obj_t * ui_Label48;
lv_obj_t * ui_Label49;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Label50;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Label51;
lv_obj_t * ui_Label52;
lv_obj_t * ui_Label53;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_Label54;
lv_obj_t * ui_Label55;
// CUSTOM VARIABLES


// SCREEN: ui_menuSCR
void ui_menuSCR_screen_init(void);
lv_obj_t * ui_menuSCR;
void ui_event_menuBTN1(lv_event_t * e);
lv_obj_t * ui_menuBTN1;
lv_obj_t * ui_Label5;
void ui_event_menuBTN2(lv_event_t * e);
lv_obj_t * ui_menuBTN2;
lv_obj_t * ui_Label6;
void ui_event_menuBTN4(lv_event_t * e);
lv_obj_t * ui_menuBTN4;
lv_obj_t * ui_Label8;
void ui_event_menuBTN5(lv_event_t * e);
lv_obj_t * ui_menuBTN5;
lv_obj_t * ui_Label9;
void ui_event_menuBTN6(lv_event_t * e);
lv_obj_t * ui_menuBTN6;
lv_obj_t * ui_Label30;
// CUSTOM VARIABLES


// SCREEN: ui_switchesSCR
void ui_switchesSCR_screen_init(void);
lv_obj_t * ui_switchesSCR;
void ui_event_bckBut2(lv_event_t * e);
lv_obj_t * ui_bckBut2;
lv_obj_t * ui_Label2;
void ui_event_SW1(lv_event_t * e);
lv_obj_t * ui_SW1;
lv_obj_t * ui_Label20;
void ui_event_SW2(lv_event_t * e);
lv_obj_t * ui_SW2;
lv_obj_t * ui_Label3;
void ui_event_SW3(lv_event_t * e);
lv_obj_t * ui_SW3;
lv_obj_t * ui_Label21;
void ui_event_SW4(lv_event_t * e);
lv_obj_t * ui_SW4;
lv_obj_t * ui_Label22;
void ui_event_SW5(lv_event_t * e);
lv_obj_t * ui_SW5;
lv_obj_t * ui_Label23;
void ui_event_SW6(lv_event_t * e);
lv_obj_t * ui_SW6;
lv_obj_t * ui_Label24;
void ui_event_SW7(lv_event_t * e);
lv_obj_t * ui_SW7;
lv_obj_t * ui_Label25;
void ui_event_SW8(lv_event_t * e);
lv_obj_t * ui_SW8;
lv_obj_t * ui_Label26;
// CUSTOM VARIABLES


// SCREEN: ui_setSCR
void ui_setSCR_screen_init(void);
lv_obj_t * ui_setSCR;
lv_obj_t * ui_Label10;
lv_obj_t * ui_deMinLBL;
lv_obj_t * ui_deHrLBL;
void ui_event_setTimeBTN1(lv_event_t * e);
lv_obj_t * ui_setTimeBTN1;
lv_obj_t * ui_Label11;
void ui_event_setTimeBTN2(lv_event_t * e);
lv_obj_t * ui_setTimeBTN2;
lv_obj_t * ui_Label12;
void ui_event_setTimeBTN3(lv_event_t * e);
lv_obj_t * ui_setTimeBTN3;
lv_obj_t * ui_Label13;
void ui_event_setTimeBTN4(lv_event_t * e);
lv_obj_t * ui_setTimeBTN4;
lv_obj_t * ui_Label14;
void ui_event_setTimeBTN5(lv_event_t * e);
lv_obj_t * ui_setTimeBTN5;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label16;
void ui_event_bckBut(lv_event_t * e);
lv_obj_t * ui_bckBut;
lv_obj_t * ui_Label17;
void ui_event_formatSWC(lv_event_t * e);
lv_obj_t * ui_formatSWC;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Label19;
lv_obj_t * ui_mainFormatLBL2;
// CUSTOM VARIABLES


// SCREEN: ui_brightnessSCR
void ui_brightnessSCR_screen_init(void);
lv_obj_t * ui_brightnessSCR;
void ui_event_bckBut1(lv_event_t * e);
lv_obj_t * ui_bckBut1;
lv_obj_t * ui_Label1;
void ui_event_Arc1(lv_event_t * e);
lv_obj_t * ui_Arc1;
lv_obj_t * ui_Label27;
lv_obj_t * ui_brightLBL;
void ui_event_saveData1(lv_event_t * e);
lv_obj_t * ui_saveData1;
lv_obj_t * ui_Label41;
// CUSTOM VARIABLES


// SCREEN: ui_offTimeSCR
void ui_offTimeSCR_screen_init(void);
lv_obj_t * ui_offTimeSCR;
void ui_event_bckBut3(lv_event_t * e);
lv_obj_t * ui_bckBut3;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Label29;
lv_obj_t * ui_offTimeLBL;
void ui_event_Slider1(lv_event_t * e);
lv_obj_t * ui_Slider1;
void ui_event_saveData3(lv_event_t * e);
lv_obj_t * ui_saveData3;
lv_obj_t * ui_Label42;
// CUSTOM VARIABLES


// SCREEN: ui_setDateSCR
void ui_setDateSCR_screen_init(void);
lv_obj_t * ui_setDateSCR;
lv_obj_t * ui_Label31;
lv_obj_t * ui_deMonthLBL;
lv_obj_t * ui_deYearLBL;
void ui_event_setDateBTN1(lv_event_t * e);
lv_obj_t * ui_setDateBTN1;
lv_obj_t * ui_Label32;
void ui_event_setDateBTN7(lv_event_t * e);
lv_obj_t * ui_setDateBTN7;
lv_obj_t * ui_Label36;
void ui_event_bckBut4(lv_event_t * e);
lv_obj_t * ui_bckBut4;
lv_obj_t * ui_Label38;
lv_obj_t * ui_deDayLBL;
void ui_event_setDateBTN2(lv_event_t * e);
lv_obj_t * ui_setDateBTN2;
lv_obj_t * ui_Label33;
void ui_event_setDateBTN3(lv_event_t * e);
lv_obj_t * ui_setDateBTN3;
lv_obj_t * ui_Label34;
void ui_event_setDateBTN4(lv_event_t * e);
lv_obj_t * ui_setDateBTN4;
lv_obj_t * ui_Label35;
void ui_event_setDateBTN5(lv_event_t * e);
lv_obj_t * ui_setDateBTN5;
lv_obj_t * ui_Label37;
void ui_event_setDateBTN6(lv_event_t * e);
lv_obj_t * ui_setDateBTN6;
lv_obj_t * ui_Label39;
lv_obj_t * ui_Label45;
lv_obj_t * ui_Label46;
lv_obj_t * ui_Label47;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_image_dsc_t * ui_imgset_1220274082[1] = {&ui_img_1970314926};
const lv_image_dsc_t * ui_imgset_73290616[1] = {&ui_img_1512711676};
const lv_image_dsc_t * ui_imgset_1373306558[1] = {&ui_img_1107282690};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_mainSWbtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        sendSwitch(e);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_switchesSCR, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_switchesSCR_screen_init);
    }
}

void ui_event_mainSWbtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        sendSwitch(e);
    }
}

void ui_event_mainSWbtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        sendSwitch(e);
    }
}

void ui_event_menuBTN1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_menuBTN2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_setDateSCR, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_setDateSCR_screen_init);
        setupDate(e);
    }
}

void ui_event_menuBTN4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_brightnessSCR, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_brightnessSCR_screen_init);
    }
}

void ui_event_menuBTN5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_offTimeSCR, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_offTimeSCR_screen_init);
    }
}

void ui_event_menuBTN6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_setSCR, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_setSCR_screen_init);
        setupSet(e);
    }
}

void ui_event_bckBut2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_SW1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        sendSwitch(e);
    }
}

void ui_event_SW2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        sendSwitch(e);
    }
}

void ui_event_SW3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        sendSwitch(e);
    }
}

void ui_event_SW4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        sendSwitch(e);
    }
}

void ui_event_SW5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        sendSwitch(e);
    }
}

void ui_event_SW6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        sendSwitch(e);
    }
}

void ui_event_SW7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        sendSwitch(e);
    }
}

void ui_event_SW8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        sendSwitch(e);
    }
}

void ui_event_setTimeBTN1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setTime(e);
    }
}

void ui_event_setTimeBTN2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setTime(e);
    }
}

void ui_event_setTimeBTN3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setTime(e);
    }
}

void ui_event_setTimeBTN4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setTime(e);
    }
}

void ui_event_setTimeBTN5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setTime(e);
    }
}

void ui_event_bckBut(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_formatSWC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        choseFormat(e);
    }
}

void ui_event_bckBut1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Arc1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        changeBRIGHT(e);
        _ui_arc_set_text_value(ui_brightLBL, target, "", "");
        _ui_arc_set_text_value(ui_brightLBL2, target, "", "");
    }
}

void ui_event_saveData1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        saveData(e);
    }
}

void ui_event_bckBut3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        changeOff(e);
        _ui_slider_set_text_value(ui_offTimeLBL, target, "", " sec");
    }
}

void ui_event_saveData3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        saveData(e);
    }
}

void ui_event_setDateBTN1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setDate(e);
    }
}

void ui_event_setDateBTN7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setDate(e);
    }
}

void ui_event_bckBut4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_setDateBTN2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setDate(e);
    }
}

void ui_event_setDateBTN3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setDate(e);
    }
}

void ui_event_setDateBTN4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setDate(e);
    }
}

void ui_event_setDateBTN5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setDate(e);
    }
}

void ui_event_setDateBTN6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setDate(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_menuSCR_screen_init();
    ui_switchesSCR_screen_init();
    ui_setSCR_screen_init();
    ui_brightnessSCR_screen_init();
    ui_offTimeSCR_screen_init();
    ui_setDateSCR_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
