// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_date_LBL;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_offBAR;
extern lv_obj_t * ui_offTimeLBL1;
extern lv_obj_t * ui_Label40;
void ui_event_mainSWbtn1(lv_event_t * e);
extern lv_obj_t * ui_mainSWbtn1;
extern lv_obj_t * ui_swLBL1;
extern lv_obj_t * ui_timeLBL;
extern lv_obj_t * ui_secLBL;
extern lv_obj_t * ui_batLBL;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_batLBL1;
extern lv_obj_t * ui_mainFormatLBL;
extern lv_obj_t * ui_swLBL2;
extern lv_obj_t * ui_swLBL3;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_batBAR;
extern lv_obj_t * ui_brightLBL2;
void ui_event_mainSWbtn2(lv_event_t * e);
extern lv_obj_t * ui_mainSWbtn2;
void ui_event_mainSWbtn3(lv_event_t * e);
extern lv_obj_t * ui_mainSWbtn3;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_yearLBL1;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_Label55;
// CUSTOM VARIABLES

// SCREEN: ui_menuSCR
void ui_menuSCR_screen_init(void);
extern lv_obj_t * ui_menuSCR;
void ui_event_menuBTN1(lv_event_t * e);
extern lv_obj_t * ui_menuBTN1;
extern lv_obj_t * ui_Label5;
void ui_event_menuBTN2(lv_event_t * e);
extern lv_obj_t * ui_menuBTN2;
extern lv_obj_t * ui_Label6;
void ui_event_menuBTN4(lv_event_t * e);
extern lv_obj_t * ui_menuBTN4;
extern lv_obj_t * ui_Label8;
void ui_event_menuBTN5(lv_event_t * e);
extern lv_obj_t * ui_menuBTN5;
extern lv_obj_t * ui_Label9;
void ui_event_menuBTN6(lv_event_t * e);
extern lv_obj_t * ui_menuBTN6;
extern lv_obj_t * ui_Label30;
// CUSTOM VARIABLES

// SCREEN: ui_switchesSCR
void ui_switchesSCR_screen_init(void);
extern lv_obj_t * ui_switchesSCR;
void ui_event_bckBut2(lv_event_t * e);
extern lv_obj_t * ui_bckBut2;
extern lv_obj_t * ui_Label2;
void ui_event_SW1(lv_event_t * e);
extern lv_obj_t * ui_SW1;
extern lv_obj_t * ui_Label20;
void ui_event_SW2(lv_event_t * e);
extern lv_obj_t * ui_SW2;
extern lv_obj_t * ui_Label3;
void ui_event_SW3(lv_event_t * e);
extern lv_obj_t * ui_SW3;
extern lv_obj_t * ui_Label21;
void ui_event_SW4(lv_event_t * e);
extern lv_obj_t * ui_SW4;
extern lv_obj_t * ui_Label22;
void ui_event_SW5(lv_event_t * e);
extern lv_obj_t * ui_SW5;
extern lv_obj_t * ui_Label23;
void ui_event_SW6(lv_event_t * e);
extern lv_obj_t * ui_SW6;
extern lv_obj_t * ui_Label24;
void ui_event_SW7(lv_event_t * e);
extern lv_obj_t * ui_SW7;
extern lv_obj_t * ui_Label25;
void ui_event_SW8(lv_event_t * e);
extern lv_obj_t * ui_SW8;
extern lv_obj_t * ui_Label26;
// CUSTOM VARIABLES

// SCREEN: ui_setSCR
void ui_setSCR_screen_init(void);
extern lv_obj_t * ui_setSCR;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_deMinLBL;
extern lv_obj_t * ui_deHrLBL;
void ui_event_setTimeBTN1(lv_event_t * e);
extern lv_obj_t * ui_setTimeBTN1;
extern lv_obj_t * ui_Label11;
void ui_event_setTimeBTN2(lv_event_t * e);
extern lv_obj_t * ui_setTimeBTN2;
extern lv_obj_t * ui_Label12;
void ui_event_setTimeBTN3(lv_event_t * e);
extern lv_obj_t * ui_setTimeBTN3;
extern lv_obj_t * ui_Label13;
void ui_event_setTimeBTN4(lv_event_t * e);
extern lv_obj_t * ui_setTimeBTN4;
extern lv_obj_t * ui_Label14;
void ui_event_setTimeBTN5(lv_event_t * e);
extern lv_obj_t * ui_setTimeBTN5;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
void ui_event_bckBut(lv_event_t * e);
extern lv_obj_t * ui_bckBut;
extern lv_obj_t * ui_Label17;
void ui_event_formatSWC(lv_event_t * e);
extern lv_obj_t * ui_formatSWC;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_mainFormatLBL2;
// CUSTOM VARIABLES

// SCREEN: ui_brightnessSCR
void ui_brightnessSCR_screen_init(void);
extern lv_obj_t * ui_brightnessSCR;
void ui_event_bckBut1(lv_event_t * e);
extern lv_obj_t * ui_bckBut1;
extern lv_obj_t * ui_Label1;
void ui_event_Arc1(lv_event_t * e);
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_brightLBL;
void ui_event_saveData1(lv_event_t * e);
extern lv_obj_t * ui_saveData1;
extern lv_obj_t * ui_Label41;
// CUSTOM VARIABLES

// SCREEN: ui_offTimeSCR
void ui_offTimeSCR_screen_init(void);
extern lv_obj_t * ui_offTimeSCR;
void ui_event_bckBut3(lv_event_t * e);
extern lv_obj_t * ui_bckBut3;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_offTimeLBL;
void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
void ui_event_saveData3(lv_event_t * e);
extern lv_obj_t * ui_saveData3;
extern lv_obj_t * ui_Label42;
// CUSTOM VARIABLES

// SCREEN: ui_setDateSCR
void ui_setDateSCR_screen_init(void);
extern lv_obj_t * ui_setDateSCR;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_deMonthLBL;
extern lv_obj_t * ui_deYearLBL;
void ui_event_setDateBTN1(lv_event_t * e);
extern lv_obj_t * ui_setDateBTN1;
extern lv_obj_t * ui_Label32;
void ui_event_setDateBTN7(lv_event_t * e);
extern lv_obj_t * ui_setDateBTN7;
extern lv_obj_t * ui_Label36;
void ui_event_bckBut4(lv_event_t * e);
extern lv_obj_t * ui_bckBut4;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_deDayLBL;
void ui_event_setDateBTN2(lv_event_t * e);
extern lv_obj_t * ui_setDateBTN2;
extern lv_obj_t * ui_Label33;
void ui_event_setDateBTN3(lv_event_t * e);
extern lv_obj_t * ui_setDateBTN3;
extern lv_obj_t * ui_Label34;
void ui_event_setDateBTN4(lv_event_t * e);
extern lv_obj_t * ui_setDateBTN4;
extern lv_obj_t * ui_Label35;
void ui_event_setDateBTN5(lv_event_t * e);
extern lv_obj_t * ui_setDateBTN5;
extern lv_obj_t * ui_Label37;
void ui_event_setDateBTN6(lv_event_t * e);
extern lv_obj_t * ui_setDateBTN6;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Label47;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1107282690);    // assets/Pictogrammers-Material-Light-Power.96.png
LV_IMG_DECLARE(ui_img_1970314926);    // assets/s-l1200.png
LV_IMG_DECLARE(ui_img_1512711676);    // assets/Custom-Icon-Design-Mono-General-4-Power.96.png

// FONTS
LV_FONT_DECLARE(ui_font_secfont);
LV_FONT_DECLARE(ui_font_small);
LV_FONT_DECLARE(ui_font_timeFont);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
