// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_brightnessSCR_screen_init(void)
{
    ui_brightnessSCR = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_brightnessSCR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_brightnessSCR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brightnessSCR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bckBut1 = lv_button_create(ui_brightnessSCR);
    lv_obj_set_width(ui_bckBut1, 137);
    lv_obj_set_height(ui_bckBut1, 70);
    lv_obj_set_x(ui_bckBut1, -95);
    lv_obj_set_y(ui_bckBut1, 175);
    lv_obj_set_align(ui_bckBut1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bckBut1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_bckBut1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_bckBut1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bckBut1, lv_color_hex(0xE21535), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bckBut1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_bckBut1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "BACK");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_brightnessSCR);
    lv_obj_set_width(ui_Arc1, 292);
    lv_obj_set_height(ui_Arc1, 311);
    lv_obj_set_x(ui_Arc1, 2);
    lv_obj_set_y(ui_Arc1, -3);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc1, 50, 255);
    lv_arc_set_value(ui_Arc1, 50);
    lv_obj_set_style_arc_width(ui_Arc1, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Arc1, 16, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_brightnessSCR);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 0);
    lv_obj_set_y(ui_Label27, -201);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "SET BRIGHTNESS");
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brightLBL = lv_label_create(ui_brightnessSCR);
    lv_obj_set_width(ui_brightLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_brightLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_brightLBL, 0);
    lv_obj_set_y(ui_brightLBL, -16);
    lv_obj_set_align(ui_brightLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_brightLBL, "40");
    lv_obj_set_style_text_font(ui_brightLBL, &ui_font_secfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_saveData1 = lv_button_create(ui_brightnessSCR);
    lv_obj_set_width(ui_saveData1, 137);
    lv_obj_set_height(ui_saveData1, 70);
    lv_obj_set_x(ui_saveData1, 95);
    lv_obj_set_y(ui_saveData1, 175);
    lv_obj_set_align(ui_saveData1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_saveData1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_saveData1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_saveData1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_saveData1, lv_color_hex(0x94A11B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_saveData1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_saveData1);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "OK");
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label41, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_bckBut1, ui_event_bckBut1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Arc1, ui_event_Arc1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_saveData1, ui_event_saveData1, LV_EVENT_ALL, NULL);

}
