// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void sendSwitch(lv_event_t * e);
void setupDate(lv_event_t * e);
void setupSet(lv_event_t * e);
void setTime(lv_event_t * e);
void choseFormat(lv_event_t * e);
void changeBRIGHT(lv_event_t * e);
void saveData(lv_event_t * e);
void changeOff(lv_event_t * e);
void setDate(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
