// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_menuSCR_screen_init(void)
{
    ui_menuSCR = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_menuSCR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menuSCR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menuSCR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuBTN1 = lv_button_create(ui_menuSCR);
    lv_obj_set_width(ui_menuBTN1, 238);
    lv_obj_set_height(ui_menuBTN1, 53);
    lv_obj_set_x(ui_menuBTN1, 0);
    lv_obj_set_y(ui_menuBTN1, -128);
    lv_obj_set_align(ui_menuBTN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menuBTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_menuBTN1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_menuBTN1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_menuBTN1, lv_color_hex(0x670D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menuBTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_menuBTN1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "HOME");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuBTN2 = lv_button_create(ui_menuSCR);
    lv_obj_set_width(ui_menuBTN2, 238);
    lv_obj_set_height(ui_menuBTN2, 53);
    lv_obj_set_align(ui_menuBTN2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menuBTN2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_menuBTN2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_menuBTN2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_menuBTN2, lv_color_hex(0x3A535A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menuBTN2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_menuBTN2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "SET DATE");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuBTN4 = lv_button_create(ui_menuSCR);
    lv_obj_set_width(ui_menuBTN4, 238);
    lv_obj_set_height(ui_menuBTN4, 53);
    lv_obj_set_x(ui_menuBTN4, 0);
    lv_obj_set_y(ui_menuBTN4, 64);
    lv_obj_set_align(ui_menuBTN4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menuBTN4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_menuBTN4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_menuBTN4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_menuBTN4, lv_color_hex(0x3A535A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menuBTN4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_menuBTN4);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "SET BRIGHTNESS");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuBTN5 = lv_button_create(ui_menuSCR);
    lv_obj_set_width(ui_menuBTN5, 238);
    lv_obj_set_height(ui_menuBTN5, 53);
    lv_obj_set_x(ui_menuBTN5, 0);
    lv_obj_set_y(ui_menuBTN5, 128);
    lv_obj_set_align(ui_menuBTN5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menuBTN5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_menuBTN5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_menuBTN5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_menuBTN5, lv_color_hex(0x3A535A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menuBTN5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_menuBTN5);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "SET OFF TIME");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menuBTN6 = lv_button_create(ui_menuSCR);
    lv_obj_set_width(ui_menuBTN6, 238);
    lv_obj_set_height(ui_menuBTN6, 53);
    lv_obj_set_x(ui_menuBTN6, 0);
    lv_obj_set_y(ui_menuBTN6, -64);
    lv_obj_set_align(ui_menuBTN6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menuBTN6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_menuBTN6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_menuBTN6, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_menuBTN6, lv_color_hex(0x3A535A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menuBTN6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_menuBTN6);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "SET TIME");
    lv_obj_set_style_text_font(ui_Label30, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_menuBTN1, ui_event_menuBTN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menuBTN2, ui_event_menuBTN2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menuBTN4, ui_event_menuBTN4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menuBTN5, ui_event_menuBTN5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_menuBTN6, ui_event_menuBTN6, LV_EVENT_ALL, NULL);

}
