// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_offTimeSCR_screen_init(void)
{
    ui_offTimeSCR = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_offTimeSCR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_offTimeSCR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_offTimeSCR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bckBut3 = lv_button_create(ui_offTimeSCR);
    lv_obj_set_width(ui_bckBut3, 137);
    lv_obj_set_height(ui_bckBut3, 70);
    lv_obj_set_x(ui_bckBut3, -95);
    lv_obj_set_y(ui_bckBut3, 175);
    lv_obj_set_align(ui_bckBut3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bckBut3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_bckBut3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_bckBut3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bckBut3, lv_color_hex(0xE21535), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bckBut3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_bckBut3);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "BACK");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label28, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_offTimeSCR);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 0);
    lv_obj_set_y(ui_Label29, -201);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "SET OFF TIME");
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_offTimeLBL = lv_label_create(ui_offTimeSCR);
    lv_obj_set_width(ui_offTimeLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_offTimeLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_offTimeLBL, 0);
    lv_obj_set_y(ui_offTimeLBL, -60);
    lv_obj_set_align(ui_offTimeLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_offTimeLBL, "5 ");
    lv_obj_set_style_text_font(ui_offTimeLBL, &ui_font_secfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_offTimeSCR);
    lv_slider_set_range(ui_Slider1, 5, 15);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 290);
    lv_obj_set_height(ui_Slider1, 35);
    lv_obj_set_x(ui_Slider1, 0);
    lv_obj_set_y(ui_Slider1, 9);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);


    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider1,
                                                                                              lv_obj_get_style_pad_right(ui_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_saveData3 = lv_button_create(ui_offTimeSCR);
    lv_obj_set_width(ui_saveData3, 137);
    lv_obj_set_height(ui_saveData3, 70);
    lv_obj_set_x(ui_saveData3, 95);
    lv_obj_set_y(ui_saveData3, 175);
    lv_obj_set_align(ui_saveData3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_saveData3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_saveData3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_saveData3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_saveData3, lv_color_hex(0x94A11B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_saveData3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label42 = lv_label_create(ui_saveData3);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "OK");
    lv_obj_set_style_text_color(ui_Label42, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label42, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_bckBut3, ui_event_bckBut3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_saveData3, ui_event_saveData3, LV_EVENT_ALL, NULL);

}
