// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_setSCR_screen_init(void)
{
    ui_setSCR = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_setSCR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setSCR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setSCR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_setSCR);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -103);
    lv_obj_set_y(ui_Label10, -184);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "SET TIME");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deMinLBL = lv_label_create(ui_setSCR);
    lv_obj_set_width(ui_deMinLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deMinLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_deMinLBL, 64);
    lv_obj_set_y(ui_deMinLBL, -10);
    lv_obj_set_align(ui_deMinLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_deMinLBL, "12");
    lv_obj_set_style_text_font(ui_deMinLBL, &ui_font_secfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deHrLBL = lv_label_create(ui_setSCR);
    lv_obj_set_width(ui_deHrLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deHrLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_deHrLBL, -64);
    lv_obj_set_y(ui_deHrLBL, -10);
    lv_obj_set_align(ui_deHrLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_deHrLBL, "12");
    lv_obj_set_style_text_font(ui_deHrLBL, &ui_font_secfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setTimeBTN1 = lv_button_create(ui_setSCR);
    lv_obj_set_width(ui_setTimeBTN1, 100);
    lv_obj_set_height(ui_setTimeBTN1, 70);
    lv_obj_set_x(ui_setTimeBTN1, -64);
    lv_obj_set_y(ui_setTimeBTN1, -90);
    lv_obj_set_align(ui_setTimeBTN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setTimeBTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_setTimeBTN1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setTimeBTN1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setTimeBTN1, lv_color_hex(0x1B73A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setTimeBTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_setTimeBTN1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "+");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_secfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setTimeBTN2 = lv_button_create(ui_setSCR);
    lv_obj_set_width(ui_setTimeBTN2, 100);
    lv_obj_set_height(ui_setTimeBTN2, 70);
    lv_obj_set_x(ui_setTimeBTN2, -64);
    lv_obj_set_y(ui_setTimeBTN2, 68);
    lv_obj_set_align(ui_setTimeBTN2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setTimeBTN2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_setTimeBTN2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setTimeBTN2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setTimeBTN2, lv_color_hex(0x1B73A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setTimeBTN2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_setTimeBTN2);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "-");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_secfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setTimeBTN3 = lv_button_create(ui_setSCR);
    lv_obj_set_width(ui_setTimeBTN3, 100);
    lv_obj_set_height(ui_setTimeBTN3, 70);
    lv_obj_set_x(ui_setTimeBTN3, 64);
    lv_obj_set_y(ui_setTimeBTN3, -90);
    lv_obj_set_align(ui_setTimeBTN3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setTimeBTN3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_setTimeBTN3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setTimeBTN3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setTimeBTN3, lv_color_hex(0x1B73A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setTimeBTN3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_setTimeBTN3);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "+");
    lv_obj_set_style_text_font(ui_Label13, &ui_font_secfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setTimeBTN4 = lv_button_create(ui_setSCR);
    lv_obj_set_width(ui_setTimeBTN4, 100);
    lv_obj_set_height(ui_setTimeBTN4, 70);
    lv_obj_set_x(ui_setTimeBTN4, 64);
    lv_obj_set_y(ui_setTimeBTN4, 68);
    lv_obj_set_align(ui_setTimeBTN4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setTimeBTN4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_setTimeBTN4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setTimeBTN4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setTimeBTN4, lv_color_hex(0x1B73A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setTimeBTN4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_setTimeBTN4);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "-");
    lv_obj_set_style_text_font(ui_Label14, &ui_font_secfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setTimeBTN5 = lv_button_create(ui_setSCR);
    lv_obj_set_width(ui_setTimeBTN5, 137);
    lv_obj_set_height(ui_setTimeBTN5, 70);
    lv_obj_set_x(ui_setTimeBTN5, 95);
    lv_obj_set_y(ui_setTimeBTN5, 175);
    lv_obj_set_align(ui_setTimeBTN5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setTimeBTN5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_setTimeBTN5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setTimeBTN5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setTimeBTN5, lv_color_hex(0x94A11B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setTimeBTN5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_setTimeBTN5);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "OK");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_setSCR);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 0);
    lv_obj_set_y(ui_Label16, -4);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, ":");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bckBut = lv_button_create(ui_setSCR);
    lv_obj_set_width(ui_bckBut, 137);
    lv_obj_set_height(ui_bckBut, 70);
    lv_obj_set_x(ui_bckBut, -95);
    lv_obj_set_y(ui_bckBut, 175);
    lv_obj_set_align(ui_bckBut, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bckBut, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_bckBut, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_bckBut, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bckBut, lv_color_hex(0xE21535), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bckBut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_bckBut);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "BACK");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_formatSWC = lv_switch_create(ui_setSCR);
    lv_obj_set_width(ui_formatSWC, 96);
    lv_obj_set_height(ui_formatSWC, 40);
    lv_obj_set_x(ui_formatSWC, 100);
    lv_obj_set_y(ui_formatSWC, -185);
    lv_obj_set_align(ui_formatSWC, LV_ALIGN_CENTER);


    ui_Label18 = lv_label_create(ui_setSCR);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 33);
    lv_obj_set_y(ui_Label18, -184);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "24");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_setSCR);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 159);
    lv_obj_set_y(ui_Label19, -184);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "12");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainFormatLBL2 = lv_label_create(ui_setSCR);
    lv_obj_set_width(ui_mainFormatLBL2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mainFormatLBL2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mainFormatLBL2, 0);
    lv_obj_set_y(ui_mainFormatLBL2, -26);
    lv_obj_set_align(ui_mainFormatLBL2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mainFormatLBL2, "PM");
    lv_obj_set_style_text_font(ui_mainFormatLBL2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_setTimeBTN1, ui_event_setTimeBTN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setTimeBTN2, ui_event_setTimeBTN2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setTimeBTN3, ui_event_setTimeBTN3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setTimeBTN4, ui_event_setTimeBTN4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setTimeBTN5, ui_event_setTimeBTN5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bckBut, ui_event_bckBut, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_formatSWC, ui_event_formatSWC, LV_EVENT_ALL, NULL);

}
