// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_setDateSCR_screen_init(void)
{
    ui_setDateSCR = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_setDateSCR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setDateSCR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setDateSCR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_setDateSCR);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, -103);
    lv_obj_set_y(ui_Label31, -184);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "SET DATE");
    lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deMonthLBL = lv_label_create(ui_setDateSCR);
    lv_obj_set_width(ui_deMonthLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deMonthLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_deMonthLBL, 0);
    lv_obj_set_y(ui_deMonthLBL, -17);
    lv_obj_set_align(ui_deMonthLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_deMonthLBL, "12");
    lv_obj_set_style_text_font(ui_deMonthLBL, &ui_font_secfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deYearLBL = lv_label_create(ui_setDateSCR);
    lv_obj_set_width(ui_deYearLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deYearLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_deYearLBL, -121);
    lv_obj_set_y(ui_deYearLBL, -17);
    lv_obj_set_align(ui_deYearLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_deYearLBL, "12");
    lv_obj_set_style_text_font(ui_deYearLBL, &ui_font_secfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setDateBTN1 = lv_button_create(ui_setDateSCR);
    lv_obj_set_width(ui_setDateBTN1, 100);
    lv_obj_set_height(ui_setDateBTN1, 70);
    lv_obj_set_x(ui_setDateBTN1, -121);
    lv_obj_set_y(ui_setDateBTN1, -95);
    lv_obj_set_align(ui_setDateBTN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setDateBTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_setDateBTN1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setDateBTN1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setDateBTN1, lv_color_hex(0x1B73A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setDateBTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_setDateBTN1);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "+");
    lv_obj_set_style_text_font(ui_Label32, &ui_font_secfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setDateBTN7 = lv_button_create(ui_setDateSCR);
    lv_obj_set_width(ui_setDateBTN7, 137);
    lv_obj_set_height(ui_setDateBTN7, 70);
    lv_obj_set_x(ui_setDateBTN7, 95);
    lv_obj_set_y(ui_setDateBTN7, 175);
    lv_obj_set_align(ui_setDateBTN7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setDateBTN7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_setDateBTN7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setDateBTN7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setDateBTN7, lv_color_hex(0x94A11B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setDateBTN7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_setDateBTN7);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "OK");
    lv_obj_set_style_text_color(ui_Label36, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label36, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bckBut4 = lv_button_create(ui_setDateSCR);
    lv_obj_set_width(ui_bckBut4, 137);
    lv_obj_set_height(ui_bckBut4, 70);
    lv_obj_set_x(ui_bckBut4, -95);
    lv_obj_set_y(ui_bckBut4, 175);
    lv_obj_set_align(ui_bckBut4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bckBut4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_bckBut4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_bckBut4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bckBut4, lv_color_hex(0xE21535), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bckBut4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_bckBut4);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "BACK");
    lv_obj_set_style_text_color(ui_Label38, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label38, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deDayLBL = lv_label_create(ui_setDateSCR);
    lv_obj_set_width(ui_deDayLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deDayLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_deDayLBL, 121);
    lv_obj_set_y(ui_deDayLBL, -18);
    lv_obj_set_align(ui_deDayLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_deDayLBL, "12");
    lv_obj_set_style_text_font(ui_deDayLBL, &ui_font_secfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setDateBTN2 = lv_button_create(ui_setDateSCR);
    lv_obj_set_width(ui_setDateBTN2, 100);
    lv_obj_set_height(ui_setDateBTN2, 70);
    lv_obj_set_x(ui_setDateBTN2, -121);
    lv_obj_set_y(ui_setDateBTN2, 64);
    lv_obj_set_align(ui_setDateBTN2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setDateBTN2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_setDateBTN2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setDateBTN2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setDateBTN2, lv_color_hex(0x1B73A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setDateBTN2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_setDateBTN2);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "-");
    lv_obj_set_style_text_font(ui_Label33, &ui_font_secfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setDateBTN3 = lv_button_create(ui_setDateSCR);
    lv_obj_set_width(ui_setDateBTN3, 100);
    lv_obj_set_height(ui_setDateBTN3, 70);
    lv_obj_set_x(ui_setDateBTN3, 0);
    lv_obj_set_y(ui_setDateBTN3, -95);
    lv_obj_set_align(ui_setDateBTN3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setDateBTN3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_setDateBTN3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setDateBTN3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setDateBTN3, lv_color_hex(0x1B73A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setDateBTN3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_setDateBTN3);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "+");
    lv_obj_set_style_text_font(ui_Label34, &ui_font_secfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setDateBTN4 = lv_button_create(ui_setDateSCR);
    lv_obj_set_width(ui_setDateBTN4, 100);
    lv_obj_set_height(ui_setDateBTN4, 70);
    lv_obj_set_x(ui_setDateBTN4, 0);
    lv_obj_set_y(ui_setDateBTN4, 64);
    lv_obj_set_align(ui_setDateBTN4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setDateBTN4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_setDateBTN4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setDateBTN4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setDateBTN4, lv_color_hex(0x1B73A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setDateBTN4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_setDateBTN4);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "-");
    lv_obj_set_style_text_font(ui_Label35, &ui_font_secfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setDateBTN5 = lv_button_create(ui_setDateSCR);
    lv_obj_set_width(ui_setDateBTN5, 100);
    lv_obj_set_height(ui_setDateBTN5, 70);
    lv_obj_set_x(ui_setDateBTN5, 121);
    lv_obj_set_y(ui_setDateBTN5, -95);
    lv_obj_set_align(ui_setDateBTN5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setDateBTN5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_setDateBTN5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setDateBTN5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setDateBTN5, lv_color_hex(0x1B73A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setDateBTN5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_setDateBTN5);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "+");
    lv_obj_set_style_text_font(ui_Label37, &ui_font_secfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setDateBTN6 = lv_button_create(ui_setDateSCR);
    lv_obj_set_width(ui_setDateBTN6, 100);
    lv_obj_set_height(ui_setDateBTN6, 70);
    lv_obj_set_x(ui_setDateBTN6, 121);
    lv_obj_set_y(ui_setDateBTN6, 64);
    lv_obj_set_align(ui_setDateBTN6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setDateBTN6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_setDateBTN6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_setDateBTN6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setDateBTN6, lv_color_hex(0x1B73A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setDateBTN6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_setDateBTN6);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "-");
    lv_obj_set_style_text_font(ui_Label39, &ui_font_secfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label45 = lv_label_create(ui_setDateSCR);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label45, -121);
    lv_obj_set_y(ui_Label45, 15);
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "YEAR");
    lv_obj_set_style_text_color(ui_Label45, lv_color_hex(0xAAA6A6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label45, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label45, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label46 = lv_label_create(ui_setDateSCR);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label46, 0);
    lv_obj_set_y(ui_Label46, 15);
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, "MONTH");
    lv_obj_set_style_text_color(ui_Label46, lv_color_hex(0xAAA6A6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label46, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label46, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label47 = lv_label_create(ui_setDateSCR);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label47, 121);
    lv_obj_set_y(ui_Label47, 12);
    lv_obj_set_align(ui_Label47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label47, "DAY");
    lv_obj_set_style_text_color(ui_Label47, lv_color_hex(0xAAA6A6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label47, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label47, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_setDateBTN1, ui_event_setDateBTN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setDateBTN7, ui_event_setDateBTN7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bckBut4, ui_event_bckBut4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setDateBTN2, ui_event_setDateBTN2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setDateBTN3, ui_event_setDateBTN3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setDateBTN4, ui_event_setDateBTN4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setDateBTN5, ui_event_setDateBTN5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setDateBTN6, ui_event_setDateBTN6, LV_EVENT_ALL, NULL);

}
