// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_switchesSCR_screen_init(void)
{
    ui_switchesSCR = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_switchesSCR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_switchesSCR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switchesSCR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bckBut2 = lv_button_create(ui_switchesSCR);
    lv_obj_set_width(ui_bckBut2, 110);
    lv_obj_set_height(ui_bckBut2, 100);
    lv_obj_set_x(ui_bckBut2, 128);
    lv_obj_set_y(ui_bckBut2, 105);
    lv_obj_set_align(ui_bckBut2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bckBut2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_bckBut2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_bckBut2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bckBut2, lv_color_hex(0xE21535), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bckBut2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_bckBut2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "BACK");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SW1 = lv_button_create(ui_switchesSCR);
    lv_obj_set_width(ui_SW1, 110);
    lv_obj_set_height(ui_SW1, 100);
    lv_obj_set_x(ui_SW1, -128);
    lv_obj_set_y(ui_SW1, -126);
    lv_obj_set_align(ui_SW1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SW1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SW1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SW1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_SW1);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "SW1");
    lv_obj_set_style_text_font(ui_Label20, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SW2 = lv_button_create(ui_switchesSCR);
    lv_obj_set_width(ui_SW2, 110);
    lv_obj_set_height(ui_SW2, 100);
    lv_obj_set_x(ui_SW2, 0);
    lv_obj_set_y(ui_SW2, -126);
    lv_obj_set_align(ui_SW2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SW2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SW2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SW2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_SW2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "SW2");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SW3 = lv_button_create(ui_switchesSCR);
    lv_obj_set_width(ui_SW3, 110);
    lv_obj_set_height(ui_SW3, 100);
    lv_obj_set_x(ui_SW3, 128);
    lv_obj_set_y(ui_SW3, -126);
    lv_obj_set_align(ui_SW3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SW3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SW3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SW3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_SW3);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "SW3");
    lv_obj_set_style_text_font(ui_Label21, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SW4 = lv_button_create(ui_switchesSCR);
    lv_obj_set_width(ui_SW4, 110);
    lv_obj_set_height(ui_SW4, 100);
    lv_obj_set_x(ui_SW4, -128);
    lv_obj_set_y(ui_SW4, -11);
    lv_obj_set_align(ui_SW4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SW4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SW4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SW4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_SW4);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "SW4");
    lv_obj_set_style_text_font(ui_Label22, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SW5 = lv_button_create(ui_switchesSCR);
    lv_obj_set_width(ui_SW5, 110);
    lv_obj_set_height(ui_SW5, 100);
    lv_obj_set_x(ui_SW5, 0);
    lv_obj_set_y(ui_SW5, -11);
    lv_obj_set_align(ui_SW5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SW5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SW5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SW5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_SW5);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "SW5");
    lv_obj_set_style_text_font(ui_Label23, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SW6 = lv_button_create(ui_switchesSCR);
    lv_obj_set_width(ui_SW6, 110);
    lv_obj_set_height(ui_SW6, 100);
    lv_obj_set_x(ui_SW6, 128);
    lv_obj_set_y(ui_SW6, -11);
    lv_obj_set_align(ui_SW6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SW6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SW6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SW6, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_SW6);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "SW6");
    lv_obj_set_style_text_font(ui_Label24, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SW7 = lv_button_create(ui_switchesSCR);
    lv_obj_set_width(ui_SW7, 110);
    lv_obj_set_height(ui_SW7, 100);
    lv_obj_set_x(ui_SW7, -128);
    lv_obj_set_y(ui_SW7, 105);
    lv_obj_set_align(ui_SW7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SW7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SW7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SW7, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_SW7);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "SW7");
    lv_obj_set_style_text_font(ui_Label25, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SW8 = lv_button_create(ui_switchesSCR);
    lv_obj_set_width(ui_SW8, 110);
    lv_obj_set_height(ui_SW8, 100);
    lv_obj_set_x(ui_SW8, 0);
    lv_obj_set_y(ui_SW8, 105);
    lv_obj_set_align(ui_SW8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SW8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SW8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SW8, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_SW8);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "SW8");
    lv_obj_set_style_text_font(ui_Label26, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_bckBut2, ui_event_bckBut2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SW1, ui_event_SW1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SW2, ui_event_SW2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SW3, ui_event_SW3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SW4, ui_event_SW4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SW5, ui_event_SW5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SW6, ui_event_SW6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SW7, ui_event_SW7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SW8, ui_event_SW8, LV_EVENT_ALL, NULL);

}
