// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x21313D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel8, 392);
    lv_obj_set_height(ui_Panel8, 537);
    lv_obj_set_x(ui_Panel8, 1);
    lv_obj_set_y(ui_Panel8, 3);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x0F0E0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x484648), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x56A0A6), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel8, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 358);
    lv_obj_set_height(ui_Panel3, 162);
    lv_obj_set_x(ui_Panel3, -4);
    lv_obj_set_y(ui_Panel3, 6);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xB2C7C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0xA3DEEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x56A0A6), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 3, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_date_LBL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_date_LBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date_LBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date_LBL, 127);
    lv_obj_set_y(ui_date_LBL, 302);
    lv_label_set_text(ui_date_LBL, "AJANUARY 1");
    lv_obj_set_style_text_color(ui_date_LBL, lv_color_hex(0x413F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date_LBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date_LBL, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel7, 149);
    lv_obj_set_height(ui_Panel7, 41);
    lv_obj_set_x(ui_Panel7, -107);
    lv_obj_set_y(ui_Panel7, -129);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xB2C7C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_offBAR = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_offBAR, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_offBAR, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_offBAR, 131);
    lv_obj_set_height(ui_offBAR, 12);
    lv_obj_set_x(ui_offBAR, -108);
    lv_obj_set_y(ui_offBAR, -118);
    lv_obj_set_align(ui_offBAR, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_offBAR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_offBAR, lv_color_hex(0x787373), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_offBAR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_offBAR, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_offBAR, lv_color_hex(0x181818), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_offBAR, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_offBAR, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_offBAR,
                                                                                             lv_obj_get_style_pad_right(ui_offBAR, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_offTimeLBL1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_offTimeLBL1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_offTimeLBL1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_offTimeLBL1, -57);
    lv_obj_set_y(ui_offTimeLBL1, -137);
    lv_obj_set_align(ui_offTimeLBL1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_offTimeLBL1, "text");
    lv_obj_set_style_text_color(ui_offTimeLBL1, lv_color_hex(0x524F4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_offTimeLBL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, -126);
    lv_obj_set_y(ui_Label40, -136);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "TURN OFF");
    lv_obj_set_style_text_color(ui_Label40, lv_color_hex(0x2F2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label40, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainSWbtn1 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_mainSWbtn1, 110);
    lv_obj_set_height(ui_mainSWbtn1, 90);
    lv_obj_set_x(ui_mainSWbtn1, -128);
    lv_obj_set_y(ui_mainSWbtn1, 163);
    lv_obj_set_align(ui_mainSWbtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainSWbtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_mainSWbtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_mainSWbtn1, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainSWbtn1, lv_color_hex(0x16364D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainSWbtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_mainSWbtn1, &ui_img_1107282690, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_mainSWbtn1, lv_color_hex(0x9EC0C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_mainSWbtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_mainSWbtn1, lv_color_hex(0x383B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_mainSWbtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_mainSWbtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainSWbtn1, lv_color_hex(0xA00E82), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_mainSWbtn1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_swLBL1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_swLBL1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_swLBL1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_swLBL1, 23);
    lv_obj_set_y(ui_swLBL1, 347);
    lv_label_set_text(ui_swLBL1, "SWITCH A");
    lv_obj_set_style_text_color(ui_swLBL1, lv_color_hex(0x9ECFE5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_swLBL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_swLBL1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeLBL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_timeLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeLBL, -29);
    lv_obj_set_y(ui_timeLBL, 11);
    lv_obj_set_align(ui_timeLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeLBL, "22:47");
    lv_obj_set_style_text_color(ui_timeLBL, lv_color_hex(0x232222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeLBL, &ui_font_timeFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_secLBL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_secLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_secLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_secLBL, 141);
    lv_obj_set_y(ui_secLBL, -19);
    lv_obj_set_align(ui_secLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_secLBL, "39");
    lv_obj_set_style_text_color(ui_secLBL, lv_color_hex(0x292828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_secLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_secLBL, &ui_font_secfont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batLBL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_batLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batLBL, -93);
    lv_obj_set_y(ui_batLBL, 54);
    lv_obj_set_align(ui_batLBL, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_batLBL, "95%");
    lv_obj_set_style_text_color(ui_batLBL, lv_color_hex(0xC2C0C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_batLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_batLBL, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button4, 187);
    lv_obj_set_height(ui_Button4, 64);
    lv_obj_set_x(ui_Button4, 71);
    lv_obj_set_y(ui_Button4, -135);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x222629), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "RELAYS");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batLBL1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_batLBL1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batLBL1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batLBL1, -133);
    lv_obj_set_y(ui_batLBL1, -161);
    lv_obj_set_align(ui_batLBL1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batLBL1, "BRIGHTNESS:");
    lv_obj_set_style_text_color(ui_batLBL1, lv_color_hex(0x9ECFE5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_batLBL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_batLBL1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainFormatLBL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_mainFormatLBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mainFormatLBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mainFormatLBL, 139);
    lv_obj_set_y(ui_mainFormatLBL, 25);
    lv_obj_set_align(ui_mainFormatLBL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mainFormatLBL, " PM ");
    lv_obj_set_style_text_color(ui_mainFormatLBL, lv_color_hex(0xCAC5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mainFormatLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mainFormatLBL, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainFormatLBL, lv_color_hex(0x0A263C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainFormatLBL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_mainFormatLBL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swLBL2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_swLBL2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_swLBL2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_swLBL2, 142);
    lv_obj_set_y(ui_swLBL2, 368);
    lv_label_set_text(ui_swLBL2, "SWITCH B");
    lv_obj_set_style_text_color(ui_swLBL2, lv_color_hex(0x9ECFE5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_swLBL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_swLBL2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swLBL3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_swLBL3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_swLBL3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_swLBL3, 260);
    lv_obj_set_y(ui_swLBL3, 347);
    lv_label_set_text(ui_swLBL3, "SWITCH C");
    lv_obj_set_style_text_color(ui_swLBL3, lv_color_hex(0x9ECFE5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_swLBL3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_swLBL3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel5, 37);
    lv_obj_set_height(ui_Panel5, 20);
    lv_obj_set_x(ui_Panel5, 137);
    lv_obj_set_y(ui_Panel5, -187);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0xCDCACA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel6, 5);
    lv_obj_set_height(ui_Panel6, 11);
    lv_obj_set_x(ui_Panel6, 158);
    lv_obj_set_y(ui_Panel6, -188);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xCDCACA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batBAR = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_batBAR, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_batBAR, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_batBAR, 29);
    lv_obj_set_height(ui_batBAR, 12);
    lv_obj_set_x(ui_batBAR, 137);
    lv_obj_set_y(ui_batBAR, -187);
    lv_obj_set_align(ui_batBAR, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_batBAR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_batBAR, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_batBAR, lv_color_hex(0x1FAE24), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_batBAR, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_batBAR, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_batBAR,
                                                                                             lv_obj_get_style_pad_right(ui_batBAR, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_brightLBL2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_brightLBL2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_brightLBL2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_brightLBL2, 128);
    lv_obj_set_y(ui_brightLBL2, 82);
    lv_label_set_text(ui_brightLBL2, "40");
    lv_obj_set_style_text_color(ui_brightLBL2, lv_color_hex(0xC2C0C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_brightLBL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_brightLBL2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainSWbtn2 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_mainSWbtn2, 110);
    lv_obj_set_height(ui_mainSWbtn2, 83);
    lv_obj_set_x(ui_mainSWbtn2, -9);
    lv_obj_set_y(ui_mainSWbtn2, 182);
    lv_obj_set_align(ui_mainSWbtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainSWbtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_mainSWbtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_mainSWbtn2, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainSWbtn2, lv_color_hex(0x16364D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainSWbtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_mainSWbtn2, &ui_img_1107282690, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_mainSWbtn2, lv_color_hex(0x9EC0C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_mainSWbtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainSWbtn2, lv_color_hex(0xA00E82), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_mainSWbtn2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_mainSWbtn3 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_mainSWbtn3, 110);
    lv_obj_set_height(ui_mainSWbtn3, 90);
    lv_obj_set_x(ui_mainSWbtn3, 109);
    lv_obj_set_y(ui_mainSWbtn3, 163);
    lv_obj_set_align(ui_mainSWbtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainSWbtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_mainSWbtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_mainSWbtn3, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainSWbtn3, lv_color_hex(0x16364D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainSWbtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_mainSWbtn3, &ui_img_1107282690, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_mainSWbtn3, lv_color_hex(0x9EC0C9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_mainSWbtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mainSWbtn3, lv_color_hex(0xA00E82), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_mainSWbtn3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 33);
    lv_obj_set_height(ui_Panel2, 90);
    lv_obj_set_x(ui_Panel2, 188);
    lv_obj_set_y(ui_Panel2, -133);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xDA2727), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x2D3031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label43 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, -4);
    lv_obj_set_y(ui_Label43, 0);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "M\nE\nN\nU");
    lv_obj_set_style_text_color(ui_Label43, lv_color_hex(0xEBEBEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label43, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 33);
    lv_obj_set_height(ui_Panel1, 86);
    lv_obj_set_x(ui_Panel1, 189);
    lv_obj_set_y(ui_Panel1, 133);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xDA2727), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x2D3031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label44 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label44, -2);
    lv_obj_set_y(ui_Label44, 0);
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "O\nN");
    lv_obj_set_style_text_font(ui_Label44, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 55);
    lv_obj_set_height(ui_Panel4, 5);
    lv_obj_set_x(ui_Panel4, 139);
    lv_obj_set_y(ui_Panel4, 3);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x383434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_yearLBL1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_yearLBL1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_yearLBL1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_yearLBL1, -126);
    lv_obj_set_y(ui_yearLBL1, 65);
    lv_obj_set_align(ui_yearLBL1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_yearLBL1, " 2025 ");
    lv_obj_set_style_text_color(ui_yearLBL1, lv_color_hex(0xCAC5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_yearLBL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_yearLBL1, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_yearLBL1, lv_color_hex(0x0A263C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_yearLBL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_yearLBL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label48 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label48, -118);
    lv_obj_set_y(ui_Label48, 218);
    lv_obj_set_align(ui_Label48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label48, "VOLOS 2025");
    lv_obj_set_style_text_color(ui_Label48, lv_color_hex(0x786E23), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label48, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label49 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label49, -79);
    lv_obj_set_y(ui_Label49, -186);
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, "HOME CONTROL");
    lv_obj_set_style_text_font(ui_Label49, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel9, 151);
    lv_obj_set_height(ui_Panel9, 6);
    lv_obj_set_x(ui_Panel9, -106);
    lv_obj_set_y(ui_Panel9, -101);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x695C18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel10, 82);
    lv_obj_set_height(ui_Panel10, 22);
    lv_obj_set_x(ui_Panel10, -125);
    lv_obj_set_y(ui_Panel10, -213);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel10, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x3C3535), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel11, 33);
    lv_obj_set_height(ui_Panel11, 18);
    lv_obj_set_x(ui_Panel11, -147);
    lv_obj_set_y(ui_Panel11, -213);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel11, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0xC91111), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label50 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label50, -147);
    lv_obj_set_y(ui_Label50, -213);
    lv_obj_set_align(ui_Label50, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label50, "ESP");

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -108);
    lv_obj_set_y(ui_Label7, -213);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "NOW");

    ui_Panel12 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel12, 179);
    lv_obj_set_height(ui_Panel12, 21);
    lv_obj_set_x(ui_Panel12, 10);
    lv_obj_set_y(ui_Panel12, -213);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x617D8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label51 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label51, -15);
    lv_obj_set_y(ui_Label51, 105);
    lv_obj_set_align(ui_Label51, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label51, "CONTROL SWITCH");
    lv_obj_set_style_text_color(ui_Label51, lv_color_hex(0x786E23), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label51, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label51, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label52 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label52, 49);
    lv_obj_set_y(ui_Label52, -213);
    lv_obj_set_align(ui_Label52, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label52, "WAVESHARE");
    lv_obj_set_style_text_color(ui_Label52, lv_color_hex(0x333030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label52, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label53 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label53, -108);
    lv_obj_set_y(ui_Label53, -59);
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, "  ESP32 S3             ");
    lv_obj_set_style_text_color(ui_Label53, lv_color_hex(0xB8C6CF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label53, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label53, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label53, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label53, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel14 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel14, 10);
    lv_obj_set_height(ui_Panel14, 21);
    lv_obj_set_x(ui_Panel14, 109);
    lv_obj_set_y(ui_Panel14, -213);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x786E23), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel15 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel15, 10);
    lv_obj_set_height(ui_Panel15, 21);
    lv_obj_set_x(ui_Panel15, 122);
    lv_obj_set_y(ui_Panel15, -213);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0x786E23), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label54 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label54, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label54, 64);
    lv_obj_set_y(ui_Label54, -88);
    lv_obj_set_align(ui_Label54, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label54, "HAPPY BIRTHDAY MAJA!");
    lv_obj_set_style_text_color(ui_Label54, lv_color_hex(0x3F5C80), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label54, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label54, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label55 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label55, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label55, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label55, 134);
    lv_obj_set_y(ui_Label55, -57);
    lv_obj_set_align(ui_Label55, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label55, "TIMEX");
    lv_obj_set_style_text_color(ui_Label55, lv_color_hex(0x3B3939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label55, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label55, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_mainSWbtn1, ui_event_mainSWbtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainSWbtn2, ui_event_mainSWbtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainSWbtn3, ui_event_mainSWbtn3, LV_EVENT_ALL, NULL);

}
